### ISSUE TITLE
load adjacent files

### ISSUE THREAD

**Issue by LloydKM** [LloydKM/CacheAdapt#4]
## Goal
If a file is opened by a program, "adjacent" files should be loaded into our layer.
## TODOs

- [x] decide on approach for json
- [x] create example json file
- [x] parse config.json file (prob with kson from klib)
- [x] load listed adjacent files into layer
- [x] test

## Discussion
- Use Program to generate config.json for given directory including all files in sub-directories.
    -> Find Library to generate list to save in json file
    -> Write own program instead
- concurrently load the adjacent files 
    -> Thread-Pool glib
    -> C++ file-loader
